import { NextRequest, NextResponse } from "next/server";
import { withAuth } from "@/lib/api-helpers";
import { prisma } from "@/lib/prisma";
import { logger } from "@/lib/logger";
import { logSecurityEvent } from "@/lib/security-log";

// GET /api/user/export-data — GDPR data portability
// Returns ALL data belonging to the authenticated user as JSON.
export async function GET(req: NextRequest) {
  return withAuth(async (userId) => {
    void logSecurityEvent({
      eventType: "data_exported",
      userId,
      request: req,
    });
    const [
      user,
      habits,
      habitLogs,
      workouts,
      personalRecords,
      bodyMetrics,
      weightLogs,
      stepsLogs,
      fastingSessions,
      challenges,
      trainingPrograms,
      readinessChecks,
      cardioSessions,
      shoes,
      bodyCompositions,
      transactions,
      budgets,
      financialAccounts,
      recurringTransactions,
      savingsGoals,
      debts,
      investments,
      pomodoroSessions,
      projects,
      focusSessions,
      foodItems,
      mealLogs,
      mealTemplates,
      recipes,
      nutritionGoal,
      bloodMarkers,
      hydrationLogs,
      bodyPhotos,
      dailyPlans,
      books,
      calendarEvents,
      calendarGroups,
      dayTemplates,
      menstrualCycles,
      periodLogs,
      milestones,
      lifeScoreSnapshots,
      netWorthSnapshots,
      badges,
      gamification,
    ] = await Promise.all([
      prisma.user.findUnique({
        where: { id: userId },
        select: {
          id: true,
          name: true,
          email: true,
          image: true,
          emailVerified: true,
          createdAt: true,
          updatedAt: true,
          profile: true,
        },
      }),
      prisma.habit.findMany({ where: { userId } }),
      prisma.habitLog.findMany({ where: { userId } }),
      prisma.workout.findMany({
        where: { userId },
        include: { exercises: { include: { sets: true } } },
      }),
      prisma.personalRecord.findMany({ where: { userId } }),
      prisma.bodyMetric.findMany({ where: { userId } }),
      prisma.weightLog.findMany({ where: { userId } }),
      prisma.stepsLog.findMany({ where: { userId } }),
      prisma.fastingSession.findMany({ where: { userId } }),
      prisma.fitnessChallenge.findMany({ where: { userId } }),
      prisma.trainingProgram.findMany({ where: { userId }, include: { phases: true } }),
      prisma.readinessCheck.findMany({ where: { userId } }),
      prisma.cardioSession.findMany({ where: { userId } }),
      prisma.shoe.findMany({ where: { userId } }),
      prisma.bodyComposition.findMany({ where: { userId } }),
      prisma.transaction.findMany({ where: { userId } }),
      prisma.budget.findMany({ where: { userId } }),
      prisma.financialAccount.findMany({ where: { userId } }),
      prisma.recurringTransaction.findMany({ where: { userId } }),
      prisma.savingsGoal.findMany({ where: { userId } }),
      prisma.debt.findMany({ where: { userId } }),
      prisma.investment.findMany({ where: { userId } }),
      prisma.pomodoroSession.findMany({ where: { userId } }),
      prisma.project.findMany({
        where: { userId },
        include: { tasks: { include: { subtasks: true } } },
      }),
      prisma.focusSession.findMany({ where: { userId } }),
      prisma.foodItem.findMany({ where: { userId } }),
      prisma.mealLog.findMany({
        where: { userId },
        include: { items: true },
      }),
      prisma.mealTemplate.findMany({ where: { userId }, include: { items: true } }),
      prisma.recipe.findMany({ where: { userId }, include: { items: true } }),
      prisma.nutritionGoal.findUnique({ where: { userId } }),
      prisma.bloodMarker.findMany({ where: { userId } }),
      prisma.hydrationLog.findMany({ where: { userId } }),
      prisma.bodyPhoto.findMany({ where: { userId } }),
      prisma.dailyPlan.findMany({
        where: { userId },
        include: { timeBlocks: true },
      }),
      prisma.book.findMany({ where: { userId }, include: { sessions: true } }),
      prisma.calendarEvent.findMany({ where: { userId } }),
      prisma.calendarGroup.findMany({ where: { userId } }),
      prisma.dayTemplate.findMany({ where: { userId } }),
      prisma.menstrualCycle.findMany({ where: { userId } }),
      prisma.periodLog.findMany({ where: { userId } }),
      prisma.milestone.findMany({ where: { userId } }),
      prisma.lifeScoreSnapshot.findMany({ where: { userId } }),
      prisma.netWorthSnapshot.findMany({ where: { userId } }),
      prisma.userBadge.findMany({ where: { userId } }),
      prisma.gamification.findUnique({ where: { userId } }),
    ]);

    if (!user)
      return NextResponse.json({ error: "No encontrado" }, { status: 404 });

    logger.info("export-data:success", { userId });

    const exportedAt = new Date().toISOString();
    const payload = {
      exportedAt,
      version: "1.0",
      user,
      gamification,
      badges,
      habits,
      habitLogs,
      workouts,
      personalRecords,
      bodyMetrics,
      weightLogs,
      stepsLogs,
      fastingSessions,
      challenges,
      trainingPrograms,
      readinessChecks,
      cardioSessions,
      shoes,
      bodyCompositions,
      transactions,
      budgets,
      financialAccounts,
      recurringTransactions,
      savingsGoals,
      debts,
      investments,
      pomodoroSessions,
      projects,
      focusSessions,
      foodItems,
      mealLogs,
      mealTemplates,
      recipes,
      nutritionGoal,
      bloodMarkers,
      hydrationLogs,
      bodyPhotos,
      dailyPlans,
      books,
      calendarEvents,
      calendarGroups,
      dayTemplates,
      menstrualCycles,
      periodLogs,
      milestones,
      lifeScoreSnapshots,
      netWorthSnapshots,
    };

    return new NextResponse(JSON.stringify(payload, null, 2), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="habit-tracker-export-${exportedAt.slice(0, 10)}.json"`,
      },
    });
  });
}
